### ISSUE TITLE
MP3Gain Express is incompatible with macOS Ventura

### ISSUE THREAD

**Issue by vigorsolair** [Sappharad/mp3gainOSX#33] opened 2022-10-30 21:43 UTC
Hi,
MP3Gain Express is incompatible with macOS Ventura and Mac m1.
Even a single mp3 stays in 'Working...' for several minutes and the app freezes with no errors.
The only way to exit the app is to click on 'force exit'.
I had no problem with macOS Monterey and Mac m1

**Comment by Sappharad** [comment] 2022-10-31 00:34
It's working perfectly fine for me on two different Macs, both Intel and M1 Max. Either you're not running the latest version (2.5, released in 2021) or you never dragged the app to your Applications folder after extracting it.

You can't run it directly from the same location that you unzip it to, it needs to be moved somewhere else.

**Closed by Sappharad** 2022-10-31 00:34 UTC

**Comment by Sappharad** [comment] 2022-11-18 03:02
If the progress bars are not moving, it doesn't matter how long you wait, just kill the app with Force Quit because they will never move. It means the UI is not getting any messages from MP3Gain on the backend and it never will. "Canceling Soon" happens because it's waiting for the backend processes to complete, but if it can't communicate with them in the first place then it doesn't know that they're not running anymore and so the window will never go away.

Have you tried deleting the app, downloading a fresh copy from my website or the releases tab on GitHub, unzipping it, moving it to Applications after unzipping, then trying it again?

**Comment by HiroiSekai** [comment] 2022-11-18 04:08
Yup, I've actually tried it with each subsequent macOS update just in case something changes, but it has not fixed it. I actually just tried again right now too.

Just as info, I'm getting it from the website. The releases tab on GitHub is empty. 
<img width="1529" alt="Screenshot 2022-11-17 at 8 07 54 PM" src="https://user-images.githubusercontent.com/44986450/202614655-8987278b-367d-4974-9863-7539ec5778bb.png">

**Comment by Sappharad** [comment] 2022-11-18 17:29
> In my case, I found that the problem was related to some mp3 files and not to "mp3 gain express" app.
> I re-econded the "defective" mp3s with "mp3 encoder" app and the "mp3 gain express" analysis ended correctly

That happened to someone else a few years ago. Although it won't be able to process "bad" files, I was at least able to address it for the particular reason those ones were failing and make it spit out an error like it should. But this is the first I've heard since then of other bad files not being rejected properly. If you know of any way to produce bad files, I'd love to look into them further so at least the problem of the app hanging can be addressed.

Ideally though, this should not happen at all and the app should be detecting that it isn't doing anything.

**Comment by HiroiSekai** [comment] 2022-11-18 20:41
Interesting alternate scenario for the cause there. I find my specific scenario to not apply, because the "Working" prompt gets stuck at random points in the procedure each time I try. However, just in case, I re-encoded my entire queue in dbPoweramp to make sure, still not working at random points.

It's a pretty bizarre issue, it does make me suspicious of a Ventura compatibility issue that isn't generalized to every user. It's always worked at 100% efficiency until Ventura. Does the app have any way to pull a diagnostic/usage log without an app crash? Maybe that may reveal something that's off.

**Comment by Sappharad** [comment] 2022-12-13 00:28
I haven't looked at it. If I can't produce the problem myself, especially if it's not consistent, I can't determine the cause to fix it.

This thread is still sitting in my inbox though, I haven't archived it. On the other hand, the "performance with large lists" bug has also been in my inbox since 2019.
